[package]
name = "code-v2"
version = "0.1.0"
edition = "2024"

[dependencies]
ed25519-dalek = { version = "2.1.0", features = ["rand_core"] }
hex = "0.4.3"
rand = "0.8.5"
sha2 = "0.10.9"
uuid = { version = "1.21.0", features = ["v4"] }
